# [generated]
# by = { compiler = "ecoscope-workflows-core", version = "9999" }
# from-spec-sha256 = "ce99aa75b964ef05abbda6aaf04196155783e7be46b4194b23de1ec97f12a9ea"

[project]
name = "ecoscope-workflows-subject-tracking-workflow"
channels = [
    "https://repo.prefix.dev/ecoscope-workflows/",
    "conda-forge",
]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
]

[system-requirements]
linux = "4.4.0"

[dependencies.fastapi]
version = "*"

[dependencies.httpx]
version = "*"

[dependencies.uvicorn]
version = "*"

[dependencies."ruamel.yaml"]
version = "*"

[dependencies.ecoscope-workflows-core]
version = "==v0.0.14"
channel = "https://repo.prefix.dev/ecoscope-workflows/"

[dependencies.ecoscope-workflows-ext-ecoscope]
version = "==v0.0.14"
channel = "https://repo.prefix.dev/ecoscope-workflows/"

[feature.test.dependencies.pytest]
version = "*"

[feature.test.tasks]
test-all = "python -m pytest -v tests"
test-app-params = "python -m pytest -v tests/test_app.py -k 'params or formdata'"
test-app-async-mock-io = "python -m pytest -v tests/test_app.py -k 'async and mock-io'"
test-app-sequential-mock-io = "python -m pytest -v tests/test_app.py -k 'sequential and mock-io'"
test-cli-async-mock-io = "python -m pytest -v tests/test_cli.py -k 'async and mock-io'"
test-cli-sequential-mock-io = "python -m pytest -v tests/test_cli.py -k 'sequential and mock-io'"

[environments.default]
features = []
solve-group = "default"

[environments.test]
features = [
    "test",
]
solve-group = "default"

[tasks]
docker-build = "docker buildx build -t ecoscope-workflows-subject-tracking-workflow ."

[pypi-dependencies.ecoscope-workflows-subject-tracking-workflow]
path = "."
editable = true
